DELETE http://localhost:8080/events/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzMzMTA3MDkzLCJ1c2VySWQiOjJ9.TWrcAVLk94gcUIIgae_Z9tvLPKP6itK7eTLYUVoHhBw