POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzMzMTExNzYwLCJ1c2VySWQiOjJ9.O8hvR3lxJ5xGCxwQ6Woy9tdeRW1SWqQSOsXG741iqq0